# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://www.joselynjk.github.io
title: Joselyn Koonamparampath
email: joselyn.josephk@gmail.com
author: Joselyn Koonamparampath
description: "Joselyn's Personal Page"

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty
# Build sitemap
gems:
  - jekyll-sitemap

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - icon: github
    title: github
    url: https://github.com/JoselynJK  
  - icon: envelope-o
    title: email
    url: mailto:joselyn.josephk@gmail.com
  - icon: linkedin
    title: linkedin
    url: https://www.linkedin.com/in/joselyn-koonamparampath-453638a0/
#  - icon: file-pdf-o
#    title: CV
#    url: img/CassolDanielaCV.pdf #add your cv here
#  - icon: website
#    title: CV Lattes
#    url: http://lattes.cnpq.br/5399100590606067
#  - icon: twitter
#    title: twitter
#    url: https://twitter.com/danicassol

